---
# tasks file for debian_11_provision, создание снапшотов
- name: Создание снапшота
  shell: "virsh snapshot-create-as --domain {{ vm_name }} --name start --description 'node prepared'"
  register: snapshot_create_status
  ignore_errors: true

- name: Вывод результатов создания
  debug:
    var: snapshot_create_status