---
# tasks file vm_provision, создание  шаблона ВМ
- name: Создание каталога {{ libvirt_pool_images }} если не существует.
  file:
    path: "{{ libvirt_pool_images }}"
    state: directory
    mode: 0755

- name: Скачивание базового образа если его нет в хранилище
  get_url:
    url: "{{ base_image_url }}"
    dest: "{{ libvirt_pool_images }}/{{ base_image_name }}"
    checksum: "sha256:{{ base_image_sha }}"  

- name: Создание копии базового образа, для шаблона
  copy:
    dest: "{{ libvirt_pool_images }}/template_with_common_settings.qcow2"
    src: "{{ libvirt_pool_images }}/{{ base_image_name }}"
    force: no
    remote_src: yes 
    mode: 0660
  register: copy_results

- name: Первичная настройка шаблона.
  command: |
    virt-customize -a {{ libvirt_pool_images }}/template_with_common_settings.qcow2 \
    --root-password password:{{ vm_root_pass }} \
    --ssh-inject 'root:file:{{ ssh_key }}' \
    --uninstall cloud-init \
    --run-command 'apt update && apt install -y ntpdate gnupg gnupg2 curl software-properties-common wget keepalived haproxy' \
    --append-line '/etc/hosts:172.30.0.201 node1.internal node1\n172.30.0.202 node2.internal node2\n172.30.0.203 node3.internal node3\n172.30.0.204 node4.internal node4\n172.30.0.205 node5.internal node5' \
    --run-command 'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/cgoogle.gpg' \
    --run-command 'apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"' \
    --run-command 'apt update && apt install -y kubeadm kubectl' \
    --run-command 'echo 'overlay' > /etc/modules-load.d/k8s.conf && echo 'br_netfilter' >> /etc/modules-load.d/k8s.conf' \
    --run-command 'echo -e "net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1\nnet.ipv4.ip_forward = 1" > /etc/sysctl.d/10-k8s.conf'

  when: copy_results is changed
